-- MySQL Script generated by MySQL Workbench
-- Tue Aug 16 20:57:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema segeDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema segeDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `segeDB` DEFAULT CHARACTER SET utf8 ;
USE `segeDB` ;

-- -----------------------------------------------------
-- Table `segeDB`.`Collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Collection` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Collection` (
  `CollectionId` INT(12) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL DEFAULT 'UABCS-PFA',
  `IsActive` TINYINT(1) NOT NULL,
  `Description` MEDIUMTEXT NULL,
  `Notes` TINYTEXT NULL,
  `Label` VARCHAR(20) NULL,
  `ProjectId` INT(4) NULL,
  PRIMARY KEY (`CollectionId`),
  INDEX `Collection_Project_idx` (`ProjectId` ASC) VISIBLE,
  CONSTRAINT `Collection_Project`
    FOREIGN KEY (`ProjectId`)
    REFERENCES `segeDB`.`Project` (`ProjectId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`ColonyType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`ColonyType` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`ColonyType` (
  `ColonyTypeId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ColonyTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`CommonNames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`CommonNames` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`CommonNames` (
  `CommonNamesId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Notes` TINYTEXT NULL,
  `LanguageId` INT(2) NOT NULL,
  PRIMARY KEY (`CommonNamesId`),
  INDEX `Name_Language_idx` (`LanguageId` ASC) VISIBLE,
  CONSTRAINT `Name_Language`
    FOREIGN KEY (`LanguageId`)
    REFERENCES `segeDB`.`Language` (`LanguageId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`ExternalLink`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`ExternalLink` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`ExternalLink` (
  `ExternalLinkId` INT NOT NULL AUTO_INCREMENT,
  `SampleId` BIGINT(16) NOT NULL,
  `Url` VARCHAR(255) NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ExternalLinkId`),
  INDEX `fk_ExternalLink_Sample1_idx` (`SampleId` ASC) VISIBLE,
  CONSTRAINT `fk_ExternalLink_Sample1`
    FOREIGN KEY (`SampleId`)
    REFERENCES `segeDB`.`Sample` (`IdentificationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Habitat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Habitat` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Habitat` (
  `HabitatId` INT NOT NULL AUTO_INCREMENT,
  `HabitatTypeId` INT NOT NULL,
  `ReefId` INT NOT NULL,
  `Lat` DECIMAL(10,8) NOT NULL,
  `Long` DECIMAL(11,8) NOT NULL,
  `WaterTempC` INT(4) NULL,
  `WaterPH` INT NULL,
  `MinDepth` INT(4) NULL,
  `MaxDepth` INT(4) NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`HabitatId`),
  INDEX `fk_Habitat_Reef1_idx` (`ReefId` ASC) VISIBLE,
  INDEX `fk_Habitat_Type_idx` (`HabitatTypeId` ASC) VISIBLE,
  CONSTRAINT `fk_Habitat_Reef1`
    FOREIGN KEY (`ReefId`)
    REFERENCES `segeDB`.`Reef` (`ReefId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habitat_Type`
    FOREIGN KEY (`HabitatTypeId`)
    REFERENCES `segeDB`.`HabitatType` (`HabitatTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`HabitatType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`HabitatType` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`HabitatType` (
  `HabitatTypeId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  `IsActive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`HabitatTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Island`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Island` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Island` (
  `IslandId` INT NOT NULL AUTO_INCREMENT,
  `RegionId` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`IslandId`),
  INDEX `fk_Island_Region1_idx` (`RegionId` ASC) VISIBLE,
  CONSTRAINT `fk_Island_Region1`
    FOREIGN KEY (`RegionId`)
    REFERENCES `segeDB`.`Region` (`RegionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Language` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Language` (
  `LanguageId` INT(2) NOT NULL AUTO_INCREMENT,
  `Language` VARCHAR(45) NOT NULL,
  `Code` VARCHAR(2) NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`LanguageId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Media` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Media` (
  `MediaId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Route` VARCHAR(255) NOT NULL,
  `Extension` VARCHAR(10) NOT NULL,
  `MediaTypeId` INT NOT NULL,
  `ResourceTypeId` INT NOT NULL,
  `ResourceKey` VARCHAR(45) NOT NULL,
  `Module` VARCHAR(45) NOT NULL,
  `SubModule` VARCHAR(45) NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  `Theme` VARCHAR(10) NULL,
  PRIMARY KEY (`MediaId`),
  INDEX `Media_Type_FK_idx` (`MediaTypeId` ASC) VISIBLE,
  INDEX `Media_ResourceType_FK_idx` (`ResourceTypeId` ASC) VISIBLE,
  CONSTRAINT `Media_Type_FK`
    FOREIGN KEY (`MediaTypeId`)
    REFERENCES `segeDB`.`MediaType` (`MediaTypeId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `Media_ResourceType_FK`
    FOREIGN KEY (`ResourceTypeId`)
    REFERENCES `segeDB`.`ResourceType` (`ResourceTypeId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`MediaType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`MediaType` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`MediaType` (
  `MediaTypeId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` TINYTEXT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`MediaTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Module` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Module` (
  `ModuleId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ModuleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Permission` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Permission` (
  `PermissionId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`PermissionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`PreservationType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`PreservationType` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`PreservationType` (
  `PreservationTypeId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`PreservationTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Project` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Project` (
  `ProjectId` INT(4) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `CollectionReference` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ProjectId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Project_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Project_User` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Project_User` (
  `ProjectId` INT(4) NOT NULL,
  `UserId` BINARY(16) NOT NULL,
  PRIMARY KEY (`ProjectId`, `UserId`),
  INDEX `fk_Project_has_user_user1_idx` (`UserId` ASC) VISIBLE,
  INDEX `fk_Project_has_user_Project1_idx` (`ProjectId` ASC) VISIBLE,
  CONSTRAINT `fk_Project_has_user_Project1`
    FOREIGN KEY (`ProjectId`)
    REFERENCES `segeDB`.`Project` (`ProjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_has_user_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `segeDB`.`user` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Reef`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Reef` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Reef` (
  `ReefId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Lat` DECIMAL(10,8) NOT NULL,
  `Long` DECIMAL(11,8) NOT NULL,
  `IslandId` INT NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`ReefId`),
  INDEX `fk_Reef_Island1_idx` (`IslandId` ASC) VISIBLE,
  CONSTRAINT `fk_Reef_Island1`
    FOREIGN KEY (`IslandId`)
    REFERENCES `segeDB`.`Island` (`IslandId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Region` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Region` (
  `RegionId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`RegionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`ResourceType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`ResourceType` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`ResourceType` (
  `ResourceTypeId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  PRIMARY KEY (`ResourceTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Role` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Role` (
  `RoleId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`RoleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Role_Permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Role_Permission` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Role_Permission` (
  `RoleId` INT NOT NULL,
  `PermissionId` INT NOT NULL,
  `ModuleId` INT NOT NULL,
  PRIMARY KEY (`RoleId`, `PermissionId`, `ModuleId`),
  INDEX `fk_Role_has_Permission_Permission1_idx` (`PermissionId` ASC) VISIBLE,
  INDEX `fk_Role_has_Permission_Role1_idx` (`RoleId` ASC) VISIBLE,
  INDEX `fk_Role_has_Permission_Module1_idx` (`ModuleId` ASC) VISIBLE,
  CONSTRAINT `fk_Role_has_Permission_Role1`
    FOREIGN KEY (`RoleId`)
    REFERENCES `segeDB`.`Role` (`RoleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Role_has_Permission_Permission1`
    FOREIGN KEY (`PermissionId`)
    REFERENCES `segeDB`.`Permission` (`PermissionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Role_has_Permission_Module1`
    FOREIGN KEY (`ModuleId`)
    REFERENCES `segeDB`.`Module` (`ModuleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Sample`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Sample` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Sample` (
  `IdentificationId` BIGINT(16) NOT NULL AUTO_INCREMENT,
  `UnitId` BIGINT(16) NOT NULL,
  `CollectionId` INT(12) NOT NULL,
  `HabitatId` INT NOT NULL,
  `ColonyTypeId` INT NULL,
  `PreservationTypeId` INT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  `CollectionReference` INT(4) NULL,
  `Description` MEDIUMTEXT NULL,
  `Notes` TINYTEXT NULL,
  `PolypColor` VARCHAR(45) NULL,
  `Size` VARCHAR(45) NULL,
  `HasDNA` TINYINT(1) NULL DEFAULT 0,
  `HasPhoto` TINYINT(1) NULL DEFAULT 0,
  `HasVideo` TINYINT(1) NULL DEFAULT 0,
  `HasArticle` TINYINT(1) NULL DEFAULT 0,
  `HasInphography` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`IdentificationId`),
  INDEX `Identification_Unit_FK_idx` (`UnitId` ASC) VISIBLE,
  INDEX `Identification_Collection_FK_idx` (`CollectionId` ASC) VISIBLE,
  INDEX `fk_Identification_Habitat1_idx` (`HabitatId` ASC) VISIBLE,
  INDEX `fk_Identification_PreservationType1_idx` (`PreservationTypeId` ASC) VISIBLE,
  INDEX `fk_Sample_ColonyType1_idx` (`ColonyTypeId` ASC) VISIBLE,
  CONSTRAINT `Identification_Unit_FK`
    FOREIGN KEY (`UnitId`)
    REFERENCES `segeDB`.`Unit` (`UnitId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Identification_Collection_FK`
    FOREIGN KEY (`CollectionId`)
    REFERENCES `segeDB`.`Collection` (`CollectionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Identification_Habitat1`
    FOREIGN KEY (`HabitatId`)
    REFERENCES `segeDB`.`Habitat` (`HabitatId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Identification_PreservationType1`
    FOREIGN KEY (`PreservationTypeId`)
    REFERENCES `segeDB`.`PreservationType` (`PreservationTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sample_ColonyType1`
    FOREIGN KEY (`ColonyTypeId`)
    REFERENCES `segeDB`.`ColonyType` (`ColonyTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`TaxCommonName`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`TaxCommonName` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`TaxCommonName` (
  `CommonNameId` INT NOT NULL,
  `TaxonId` INT(12) NOT NULL,
  PRIMARY KEY (`CommonNameId`, `TaxonId`),
  INDEX `fk_CommonNames_has_Taxon_Taxon1_idx` (`TaxonId` ASC) VISIBLE,
  INDEX `fk_CommonNames_has_Taxon_CommonNames1_idx` (`CommonNameId` ASC) VISIBLE,
  CONSTRAINT `fk_CommonNames_has_Taxon_CommonNames1`
    FOREIGN KEY (`CommonNameId`)
    REFERENCES `segeDB`.`CommonNames` (`CommonNamesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CommonNames_has_Taxon_Taxon1`
    FOREIGN KEY (`TaxonId`)
    REFERENCES `segeDB`.`Taxon` (`TaxonId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Taxon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Taxon` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Taxon` (
  `TaxonId` INT(12) NOT NULL AUTO_INCREMENT,
  `TaxonTypeId` SMALLINT(3) NOT NULL,
  `TaxFatherId` BINARY(16) NULL,
  `Name` VARCHAR(45) NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`TaxonId`),
  INDEX `Taxon_Type_FK_idx` (`TaxonTypeId` ASC) VISIBLE,
  CONSTRAINT `Taxon_Type_FK`
    FOREIGN KEY (`TaxonTypeId`)
    REFERENCES `segeDB`.`TaxonType` (`TaxonTypeId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`TaxonType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`TaxonType` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`TaxonType` (
  `TaxonTypeId` SMALLINT(3) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` TINYTEXT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  `LanguageId` INT(2) NOT NULL,
  PRIMARY KEY (`TaxonTypeId`),
  INDEX `TaxonType_Language_FK_idx` (`LanguageId` ASC) VISIBLE,
  CONSTRAINT `TaxonType_Language_FK`
    FOREIGN KEY (`LanguageId`)
    REFERENCES `segeDB`.`Language` (`LanguageId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`TrackingResource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`TrackingResource` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`TrackingResource` (
  `TrackingResourceId` INT NOT NULL AUTO_INCREMENT,
  `TrackingTypeId` INT NOT NULL,
  `ResourceTypeId` INT NOT NULL,
  `ResourceKey` VARCHAR(45) NOT NULL,
  `UserId` BINARY(16) NOT NULL,
  `EventDate` TIMESTAMP NOT NULL,
  PRIMARY KEY (`TrackingResourceId`),
  INDEX `Tracking_Type_FK_idx` (`TrackingTypeId` ASC) VISIBLE,
  INDEX `Tracking_ResourceType_FK_idx` (`ResourceTypeId` ASC) VISIBLE,
  INDEX `Tracking_User_FK_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `Tracking_Type_FK`
    FOREIGN KEY (`TrackingTypeId`)
    REFERENCES `segeDB`.`TrackingType` (`TrackingTypeId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `Tracking_ResourceType_FK`
    FOREIGN KEY (`ResourceTypeId`)
    REFERENCES `segeDB`.`ResourceType` (`ResourceTypeId`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `Tracking_User_FK`
    FOREIGN KEY (`UserId`)
    REFERENCES `segeDB`.`user` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`TrackingType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`TrackingType` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`TrackingType` (
  `TrackingTypeId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TrackingTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`Unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`Unit` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`Unit` (
  `UnitId` BIGINT(16) NOT NULL AUTO_INCREMENT,
  `TaxonId` INT(12) NOT NULL,
  `Description` MEDIUMTEXT NULL,
  `Notes` TINYTEXT NULL,
  `IsActive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`UnitId`),
  INDEX `Unit_Taxon_idx` (`TaxonId` ASC) VISIBLE,
  CONSTRAINT `Unit_Taxon`
    FOREIGN KEY (`TaxonId`)
    REFERENCES `segeDB`.`Taxon` (`TaxonId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`User_Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`User_Role` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`User_Role` (
  `UserId` BINARY(16) NOT NULL,
  `RoleId` INT NOT NULL,
  PRIMARY KEY (`UserId`, `RoleId`),
  INDEX `fk_user_has_Role_Role1_idx` (`RoleId` ASC) VISIBLE,
  INDEX `fk_user_has_Role_user1_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_Role_user1`
    FOREIGN KEY (`UserId`)
    REFERENCES `segeDB`.`user` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_Role_Role1`
    FOREIGN KEY (`RoleId`)
    REFERENCES `segeDB`.`Role` (`RoleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `segeDB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `segeDB`.`user` ;

CREATE TABLE IF NOT EXISTS `segeDB`.`user` (
  `UserId` BINARY(16) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `IsActive` TINYINT(1) NOT NULL DEFAULT 1,
  `Name` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `LastName2` VARCHAR(45) NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
